### ISSUE TITLE
Question: [Asking About Your Compiler Project]

### ISSUE THREAD

**Issue by aniketambore** [BaseMax/BaseMax#8]
Are you creating your Compiler Project using **Low Level Programming Language** .?
If not ~~Low Level Programming Language~~ then, Could you specify the path that 
---
- How/When you started to working on your Compiler Project?
- What is the aim of your Compiler / _The Final Product_ ?

**Comment by BaseMax** [comment]
Hi Aniket @aniketambore 

So far, I have been involved in various languages.
But what am I looking for? It is a new language that can meet other needs.

Maybe the things I mention are also mentioned in the compiler books.
But it is important that we come to believe this.
This is not impossible. It is quite possible.

> How you started working on your Compiler Project?

The idea came to me about 9-10 years ago. There is still no suitable programming language to meet their needs.
In addition to meeting the needs, the development team is also important.

Long way from interpreter / code generator / assembly code generation / machine code generation / LLVM and ...

> When you started working on your Compiler Project?

We have had such a plan and idea in mind for more than 7 years.

> What is the aim of your Compiler / The Final Product?

A new and modern programming language so that you can produce real programs with it.


> Simple, fast, safe, compiled, empowering everyone to build efficient and reliable software.

**Simple:**
Most compiler languages ​​are not simple enough for beginners. (Or even for professional programmers)

This may be appropriate for **Linus Torvalds**. But not for me and many others.
We write programs full of bugs. I still write weird bugs.

Simple language does not mean removing tokens.

Some people think that reducing the number of tokens means simplicity...
This can confuse readers in the future.
The code must be highly readable. (Clean syntax, grammar)

We will need a lot of software packages and plugins.
Something that is not yet complete.

**Fast:**
Good performance against other programming languages. (Translators and compilers)

for e.g: Have you seen many scientists using Python for computational applications?
It is still slow and can not help them to perform well.

A fast compiler is not a fully optimized compiler.

On the other hand, I prefer the compiler to work fast.
(Also have a reasonable degree of optimization)

A fast compiler is great, you can easily develop, run, and build big projects in less than 1 second.

So where is great performance?

I want to be able to generate Another output code along with the compiler.
In this case, others can also use powerful optimizers such as clang, GCC, If they do not trust this optimizer in production.

So I think we should have an internal compiler and an external compiler.
There is a need for both. That was my argument.
Maybe you have another opinion. Glad to know your opinion.

**Safe:**

Many programmers repeat bugs and problems in the compiler language. And this is what we want to do for programmers to follow a universal style of programming. We have removed some common features in programming languages.
However, this can help in the development time cycle.

Easy to write code, Easy to develop and maintain, A **package manager,** Support common Operation systems, Tiny and small size, Design website using the programming language.

Empowering everyone to build efficient and reliable software, is not a simple goal. It's what I want to reach...

### Concluding remarks

After all these years, I can admit that I made many mistakes for this project.
It would have been better if we had even released it as an interpreter in the beginning.
In addition to helping others, it could also engage the user community.

But this is not professionally true. Because the language must reach a stable version.
Otherwise, it is not wise to use it!

Eventually. It does not matter if your compiler is based on LLVM or compiler C or any other way ...
The question is, can it help programmers produce better software?

I spoke to one of the Rust core team developers several years ago. He told me such a thing.
I understand this better now.

Forgive me. Sorry for my typos mistakes, this was a long text.

This year I want to publish a usable version of the compiler. Even if it is small and incomplete.

Hope a better day for developing software.

However, there is no budget or money for this. While we really need money.

The things I mentioned were all relative.
So we are full of problems. But we are not disappointed and we must be prepared.
And be developed step by step. To get closer to the ultimate goal and this is achieved with the help of others.

Cheers,
